#!/usr/bin/env bash


workDir="$HOME/.cache/ximg"
[ ! -d "$workDir" ] && mkdir -p "$workDir"

case "$1" in
  "-c")
    imgDir="/storage/emulated/0/DCIM/OpenCamera"
    ;;
  "-co")
    imgDir="/storage/emulated/0/DCIM/OpenCamera"
    open=1
    ;;
  "-o")
    imgDir="/storage/emulated/0/Pictures/temp"
    open=1
    ;;
  "-r")
    nvim -c "set spell" "$workDir/output.txt"
    exit
    ;;
  *)
    imgDir="/storage/emulated/0/Pictures/temp"
    ;;
esac

rm -rf "$workDir/img.jpg"

latestImg="$(ls -tr "$imgDir" | tail -n 1)"

magick "$imgDir/$latestImg" \
  -alpha off \
  -density 250 \
  -statistic median 3x3 \
  -normalize \
  +dither -colors 3 -colors 2 \
  -colorspace gray \
  "$workDir/img.jpg"

tesseract "$workDir/img.jpg" "$workDir/output"

if [[ -n "$open" ]]; then
  nvim -c "set spell" "$workDir/output.txt"
else
  cat "$workDir/output.txt" | termux-clipboard-set
fi
