#!/usr/bin/env bash

HELPDIR="$HOME/bin/help"
BINDIR="$HOME/bin"
LIBDIR="$HOME/bin/lib"
TRASHCAN="$HOME/.trash"

chkdir () {
  if [[ ! -d "$1" ]]; then
    mkdir -p "$1"
  fi
}

chkdir "$HELPDIR"
chkdir "$BINDIR"
chkdir "$LIBDIR"
chkdir "$TRASHCAN"

viewhelp () {
  echo ""
  while read line; do
    if [[ "$line" =~ ^- ]]; then
      echo "$line" |\
        awk -F '::' '{printf "%s\n%s\n\n", $1, $2}' |\
        fold -w45 -s |\
        sed "s/^[a-zA-Z]/`printf "%-7s"`&/; s/^-/`printf "%-3s"`&/"
    elif [[ "$line" =~ ^[a-zA-Z] ]] && ! [[ "$line" =~ : ]]; then
      echo "$line" |\
        fold -w45 -s |\
        sed "s/^[a-zA-Z]/`printf "%-3s"`&/"
    else
      echo "$line"
    fi
  done < $HELPDIR/${1##*/}
}

# ===========================================
# Tmux macros
# ===========================================
rmsess () { tmux kill-session -t "$1" ;}
mksess () { tmux new-session -d -s "$1" ;}
mkonlysess () { 
  if [ "`issess $1`" == "true" ];then
    rmsess $1
    tmux new-session -d -s "$1"
  else
    tmux new-session -d -s "$1"
  fi
}
issess () { 
  tmux has-session -t "$1" 2>/dev/null
  if [ "$?" == "0" ]; then
    echo "true"
  else
    echo "false"
  fi
}
mkwin () { tmux new-window -n "$2" -t "$1": "$3" ;}
mkwin1 () { 
  tmux new-window -n "$2" -t "$1": "$3"
  tmux kill-window -t "$1":"1"
}
selwin () { tmux select-window -t "$1":"$2" ;}
rmwin () { tmux kill-window -t "$1":"$2" ;}
selsess() { tmux switch -t $1 ;}

# ===========================================
# ADB macros
# ===========================================
ads () { adb -s localhost:5555 shell $@ ;}

bluetooth () { ads cmd bluetooth_manager $1 ;}
airplane () { ads cmd connectivity airplane-mode $1 ;}
wifi () { ads cmd wifi set-wifi-enabled $1 ;}
wifi_status () { ads cmd wifi status | sed -n 1p | awk '{print $3}' ;}
greyscale () { ads settings put secure accessibility_display_daltonizer_enabled $1 ;}
block_cam () { ads service call sensor_privacy 10 i32 0 i32 0 i32 2 i32 $1 ;}
block_mic () { ads service call sensor_privacy 10 i32 0 i32 0 i32 1 i32 $1 ;}


# ===========================================
# Notifications
# ===========================================
toaster () { termux-toast -g "$1" -c "#F48FB1" -b "#D0000000" "$2" ;}
